title: Kerry Yu
description: quux
theme: just-the-docs

url: https://kerryyu.github.io/person

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template


just_the_docs:
  css:
    - /assets/css/custom.css
